version: '3'
services:
  gateway:
    build:
      context: gateway
      dockerfile: ./Dockerfile
    image: arrrspace-gateway
    ports:
      - "8000:8080"
      - "9876:9876"
    environment:
      - GATEWAY_HOSTNAME=${GATEWAY_HOSTNAME}
      - STATIC_SITE_HOSTNAME=${STATIC_SITE_HOSTNAME}
    networks:
      - eg
networks:
  eg:
