apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deploy-manager-role
rules:
  - apiGroups:
      - '*'
    resources:
      - 'deployments'
      - 'replicasets'
      - 'pods'
      - 'secrets'
    verbs:
      - '*'
