apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deploy-manager-role
rules:
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "update"
