apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 31337 
  selector:
    io.kompose.service: gateway
status:
  loadBalancer: {}
