http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  index:
    host: '*'
    paths: ['/']
  jenkins:
    host: '*'
    paths: ['/jenkins/*']
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints
serviceEndpoints:
  indexProxy:
    url: "http://localhost:9100"
  jenkinssvc:
    url: "http://jenkinssvc:8080"
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/serviceEndpoints
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - rewrite
pipelines:
  index:
    apiEndpoints:
      - index
    policies:
      -
        proxy:
          - action:
              serviceEndpoint: indexProxy
  jenkins:
    apiEndpoints:
      - jenkins 
    policies:
      -
        log:
          - action:
              message: ${req.method} ${req.originalUrl}
      -
        rewrite:
          -
            condition:
              name: regexpmatch
              match: ^/jenkins/(.*)$
            action:
              rewrite: /$1
      -
        proxy:
          -
            action:
              serviceEndpoint: jenkinssvc
  
  # see: https://www.express-gateway.io/docs/configuration/gateway.config.yml/pipelines
